### PR TITLE
Reduce overhead of fold

### PR DESCRIPTION
**Pull request by tvh**
This addresses issue 3 of 6457e41491a256ffbbfefd470039e2fd3310a931.

This is not thoroughly tested yet.

### CODE REVIEW

**Comment by lpsmith** [comment]
Looks promising...  although one thing I'm not sure I agree with here is the use of the state monad in `go`,   I think that putting an explicit accumulator on `loop` and using `forM` instead of `forM_` would be clearer and possibly a touch faster.

Also speaking of `forM_`,  you are creating a superfluous list there.   As in,  I'm pretty sure this list is created with older versions of GHC,  like 7.6,  though this _might_ be fixed in 7.8 or 7.10, I'm not sure which one introduced the `foldl` fusion stuff which _might_ have also implemented `forM_` / `forM` fusion.    IIRC,  there's a special-cased variant of `forM_` in postgresql-simple somewhere,  I'm not sure if this function would be applicable here.

**Comment by lpsmith** [comment]
Ok,  yeah the function I am talking about is [`forM'`](https://github.com/lpsmith/postgresql-simple/blob/6457e41491a256ffbbfefd470039e2fd3310a931/src/Database/PostgreSQL/Simple.hs#L438) and it's not applicable to this situation.   We'll probably need to create a similar function,  possibly giving `forM'` a better name too.

**Comment by tvh** [comment]
As far as I know the state monad should not add any overhead on runtime. Not using it may make things more clear though. I adjusted the code to use explicit recursion.

**Comment by lpsmith** [comment]
I'll clean this up a little,  but it looks good.  Thank you!

**Comment by lpsmith** [comment]
(Also, I meant `foldM` at a couple of spots in my comment above when I said `forM`)

**Pull request merged**
