### PR TITLE
Implement default instances for {To,From}Row using Generic

### PR DESCRIPTION
**Pull request by Shimuuar**
Writing instance for {To,From}Row is verbose, tedious, and should be left to compiler. I wrote deriving of such instances using Generic. I've also put lower bound on base (GHC>=7.2 when Generics appeared)

There's no tests. I couldn't figure out how to run RowParser on [Field]

### CODE REVIEW

**Comment by lpsmith** [comment]
>   I couldn't figure out how to run RowParser on [Field]

What do you mean?

**Comment by Shimuuar** [comment]
Hot to write function with type `RowParser a → [Action] → MaybeOrSomethingElse a` in order to check roundtripping

**Comment by lpsmith** [comment]
My apologies for not getting around to this in a timely fashion;   I've been meaning to take a careful look at this pull request for a few days now.    I probably will merge it as soon as I can.

**Comment by Shimuuar** [comment]
Anyway I think it's good idea to add tests to verify that derived instances are correct. But I have to idea how to write them.

**Comment by lpsmith** [comment]
I think I see what you mean now.   And yes,  for the moment at least,  there isn't really a way to test a `RowParser` without obtaining a postgresql-libpq `Result`,  and (for the moment at least?)  there isn't any way to construct a `Result` without talking to something that speaks the postgres protocol.

However,  the test suite is already assumes it is talking to a postgres database,  so what I'd probably do is something like the following:

~~~
data TestGeneric = Foo { ga :: Int, gb :: Text, gc :: Double } deriving (Eq, Generic)

instance FromRow TestGeneric

testGenericRoundTrip :: TestEnv -> TestGeneric -> IO ()
testGenericRoundTrip TestEnv{..} g = do
    gs :: [TestGeneric] <- query conn [sql| SELECT ?::int, ?::text, ?::float8 |] (ga g, gb g, gc g) 
    gs @?= [g]
~~~

**Comment by Shimuuar** [comment]
I finally got time to add tests.

**Comment by lpsmith** [comment]
Thanks!

**Pull request merged**
