### PR TITLE
Add alternate streaming functions that take a RowParser as an argument

### PR DESCRIPTION
**Pull request by tstat**
Follows the conventions established #89.

### CODE REVIEW

**Comment by tstat** [comment]
My motivation for this change is to allow higher level libraries (like opaleye) to make use of the streaming functions.

**Comment by lpsmith** [comment]
Sorry for not responding sooner.   I agree the use case is important,  but it's also seems as though there's an undesirable exponential explosion in the number of functions here.

I was wondering if there is a way to use some of GHC's extensions to  do what you want without changing postgresql-simple,  and without having to define a newtype for each RowParser.   I don't think it is possible with some of the tricks I was trying to recall;  and then there is the legitimate question of whether one really wants to rely on said tricks.     Even if the consequences on GHC's code generation are minimal or nonexistent,  it shouldn't be too difficult to use the library either.

Let me think about it a bit for another week,   if I don't come up with a reasonable answer,  I'll merge this patch.

**Comment by lpsmith** [comment]
Yeah, I really don't see an obvious way to accomodate this use case without adding these functions.  Thanks!

**Comment by tomjaguarpaw** [comment]
Any update on this?  I'd love to add streaming support to Opaleye.

**Comment by tomjaguarpaw** [comment]
Since the patch has been merged I guess I'm asking if there can be a Hackage release!

**Comment by lpsmith** [comment]
Yeah,  I need to release;  the holdup has been that it's version 0.5 and I still have a few more breaking changes I want to complete.   But there's already a lot of changes,  see ee417bd3967d9519bb74b26c56c3f19a4ecd99dd.  (I didn't totally forget about this change; I wrote a blurb about in the next commit 52ba5dab2a817836d16066df14606a0fb6850aff.)

**Pull request merged**
